 



export const getAllProducts = async (req, res, next)=> {
    try{                
        res.status(200).send("user has been created!")    
    }catch(err){
       console.log("we in controller error",err)
       
    }


}

export const addProducts = async (req, res, next)=> {
    try{                
        res.status(200).send("Warehouse has been created!")    
    }catch(err){
       console.log("we in controller error",err)
       
    }


}

export const  editProducts  = async (req, res, next)=> {
    try{                
        res.status(200).send("user has been created!")    
    }catch(err){
       console.log("we in controller error",err)
       
    }


}

export const deleteProducts = async (req, res, next)=> {
    try{                
        res.status(200).send("user has been created!")    
    }catch(err){
       console.log("we in controller error",err)
       
    }


}